"""empty message

Revision ID: e7b7ef4bcb7d
Revises: 76e0ddf51e5f
Create Date: 2022-10-15 03:04:09.493018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b7ef4bcb7d'
down_revision = '76e0ddf51e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('person', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('person', 'name')
    # ### end Alembic commands ###
